name: "Continuous Integration"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use oxr463/setup-cordova
      uses: ./
      with:
        exec: |
          cordova create hello com.example.hello HelloWorld && \
          cd hello && \
          cordova platform add android && \
          cordova build --no-telemetry && \
          cp "$(find . -name '*.apk')" .
